Draft: Book Features chapter (#55, #64, #102, #103, #123)
cucumber-rs/cucumber pull request #132
Opened 2021-09-28 13:44 UTC by ilslv

Resolves #55, #64, #102, #103, #123

## Synopsis

New features can be tricky to find, especially at the beginning.

## Solution

Add `Features` and `Test Modules Organisation` chapters to the book. 

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-09-29 06:34 UTC, ilslv commented
## FCM

```
Add Features and Test Modules Organization chapters to the book (#55, #64, #102, #103, #123, #132)

Additionally:
- output parsed keywords instead of english in writer::Basic
```

2021-09-29 11:56 UTC, tyranron requested changes
@ilslv some more clear code examples are required, anything else seems to be OK.

2021-09-29 11:56 UTC, tyranron commented on book/src/Test_Modules_Organization.md
> +And, as time goes on, total run time of all tests can become overwhelming when you only want to test small subset of `Scenario`s. At least until you discover [`Cucumber::filter_run_and_exit()`](https
This case and the above requires code examples. It hard to grasp the thing without them. Please, add the code examples directly to rate docs, so the provided links will lead there.

2021-09-30 08:31 UTC, tyranron approved these changes

2021-09-30 08:34 UTC, merged