Pass the `World` to after hook even if `Step` has failed (#207)
cucumber-rs/cucumber pull request #209
Opened 2022-03-11 06:10 UTC by ilslv

Resolves #207

## Synopsis

For now `after` hook accepts mutable reference to the `World` instance, but only in case `Step` didn't fail.

## Solution

Accept shared reference to the `World` instance (it's ok because it's not passed on either way) and pass it even in case  `Step` has failed.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-03-11 06:12 UTC, ilslv commented
## FCM

```
Pass the `World` to `after` hook even if `Step` has failed (#209, #207)

- receive shared reference to the `World` in `after` hook callback
```

2022-03-11 09:36 UTC, tyranron requested changes
Discussed to preserve `&mut World` in After Hook.

2022-03-25 11:11 UTC, ilslv commented
I've left changes in `0.13` release inside `CHANGELOG.md`, because despite stability of the API, behaviour of `Hook::After` have changed and theoretically can break user code (for example assertions about number of passed/failed hooks), but I'm not sure about this decision. [semver](https://semver.org) doesn't specify what to do in this case.

2022-03-25 11:12 UTC, tyranron commented
@ilslv I'd opt for going with patch release for that.

2022-03-25 14:29 UTC, tyranron approved these changes

2022-03-25 14:29 UTC, tyranron commented on src/runner/basic.rs
> +            //       `HookType::After` was started.
@ilslv I don't see why we should postpone this. Please, fix in a separate PR.

2022-03-25 14:42 UTC, merged