Draft: Retry failed `Scenario`s
cucumber-rs/cucumber pull request #223
Opened 2022-07-22 10:09 UTC by ilslv

Resolves #212

## Synopsis

For now there is no way to retry failed `Scenario`s. 

## Solution

Implement ability to implement retries of failed `Scenario`s with:
1. Tags `@retry`/`@retry(3)`/`@retry.after(3s)`/`@retry(5).after(all)`2. 
2. CLI options `--retry=3`/`--retry-after=30ms`/`--retry-after=all`

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests
[format]: https://github.com/rust-lang/rust/issues/49359

2022-08-11 13:47 UTC, ilslv commented
## FCM

```
Retry failed `Scenario`s (#223, #212)
```

2022-08-19 09:05 UTC, tyranron requested changes

2022-08-19 09:05 UTC, tyranron commented on src/runner/basic.rs
> +    R = RetryOptionsFn,
@ilslv maybe we could just `Box<dyn FnMut>` here instead of introducing yet another type parameter? Doesn't seem to be critical.

2022-08-19 09:05 UTC, tyranron commented on src/runner/basic.rs
> +                                after.strip_prefix('(').and_then(|after| {
@ilslv would be nice to refactor tags parsing into a separate function on `RetryOptions`, and so cover it with unit tests.

2022-09-08 15:58 UTC, tyranron approved these changes

2022-09-08 16:11 UTC, merged